
-- CREATE STREAM
CREATE STREAM YOUTUBE_VIDEOS (
  VIDEO_ID STRING KEY,
  TITLE STRING,
  LIKES INT,
  COMMENTS INT,
  VIEWS INT,
  FAVORITES INT,
  THUMBNAIL STRING
) WITH (
  KAFKA_TOPIC = 'youtube_videos',
  PARTITIONS = 1,
  VALUE_FORMAT = 'JSON'
);


