
-- CREATE STREAM
CREATE STREAM YOUTUBE_VIDEOS (
  VIDEO_ID STRING KEY,
  TITLE STRING,
  LIKES INT,
  COMMENTS INT,
  VIEWS INT,
  FAVORITES INT,
  THUMBNAIL STRING
) WITH (
  KAFKA_TOPIC = 'youtube_videos',
  PARTITIONS = 1,
  VALUE_FORMAT = 'JSON'
);


SELECT * FROM YOUTUBE_VIDEOS;

CREATE TABLE YOUTUBE_ANALYTICS_CHANGE WITH (KAFKA_TOPIC='YOUTUBE_ANALYTICS_CHANGE') AS
SELECT VIDEO_ID,LATEST_BY_OFFSET(TITLE) AS TITLE,
LATEST_BY_OFFSET(COMMENTS,2)[1] AS COMMENTS_CURR, 
LATEST_BY_OFFSET(COMMENTS,2)[2] AS COMMENTS_PREV, 
LATEST_BY_OFFSET(LIKES,2)[1] AS LIKES_CURR,
LATEST_BY_OFFSET(LIKES,2)[2] AS LIKES_PREV,
LATEST_BY_OFFSET(VIEWS,2)[1] AS VIEWS_CURR,
LATEST_BY_OFFSET(VIEWS,2)[2] AS VIEWS_PREV,
LATEST_BY_OFFSET(FAVORITES,2)[1] AS FAVORITES_CURR,
LATEST_BY_OFFSET(FAVORITES,2)[2] AS FAVORITES_PREV
FROM YOUTUBE_VIDEOS 
GROUP BY VIDEO_ID;


SELECT * FROM YOUTUBE_ANALYTICS_CHANGE
WHERE LIKES_PREV <> LIKES_CURR
EMIT CHANGES;

CREATE STREAM TELEGRAM_OUTPUT_STREAM (
  `CHAT_ID` VARCHAR,
  `TEXT` VARCHAR
) WITH (
  KAFKA_TOPIC = 'TELEGRAM_OUTPUT_STREAM',
  PARTITIONS = 1,
  VALUE_FORMAT = 'AVRO'
);


INSERT INTO TELEGRAM_OUTPUT_STREAM
SELECT '7895487890' AS CHAT_ID,
       CONCAT('LIKES CHANGED FOR ',
              TITLE,
              ' - ',
              CAST(LIKES_PREV AS STRING),
              ':',
              CAST(LIKES_CURR AS STRING)
       ) AS TEXT
FROM YOUTUBE_ANALYTICS_CHANGE
WHERE LIKES_PREV <> LIKES_CURR;
